[package]
name = "Crab2D"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Crab2D"
test = false
bench = false

[dependencies]
gba = "0.15.0"

[profile.dev]
opt-level = 3
incremental = false

[profile.release]
codegen-units = 1
opt-level = 3
incremental = false
