[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]

[target.thumbv4t-none-eabi]
runner = ["env", "QT_LOGGING_RULES=*.warning=false", "mgba-qt", "-C", "logToStdout=1", "-C", "logLevel.gba.debug=127"]
rustflags = [
  "-Clinker=arm-none-eabi-ld",
  "-Clink-arg=-Tlinker_scripts/mono_boot.ld",
  "--emit=mir",
]
